config/routes.rb
Forgetmenot::Application.routes.draw do
  devise_for :users
  root to: "site#root"

  namespace :api, :defaults => { :format => :json } do
    resources :users, only: [:index, :show]
    resources :relationships, only: [:create, :index, :update, :destroy]
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower
  belongs_to :followed_user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/relationships_controller.rb
class Api::RelationshipsController < ApplicationController
  def create
    @relationship = Relationship.new(relationship_params)

    if @relationship.save
      render json: @relationship
    else
      render json: @relationship.errors.full_messages, status: 402
    end 
  end

  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    render "relationships/destroy"
  end

  def index
    @relationships = Relationship.all
    render "relationships/index"
  end

  def update
    @relationship = Relationship.find(params[:id])
    @relationship.update_attributes(relationship_params)
    render "relationships/show"
  end

  private
  def relationship_params
    params.require(:relationship).permit(:liker_id, :liked_user_id, :last_contact)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.json { render json: @user }
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :phone_number)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Expose these methods to the views
  helper_method :current_user, :signed_in?

  private

  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_session_token(session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to user_url(current_user) if signed_in?
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def root
    render "root"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token_input
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{ form_authenticity_token }\">".html_safe
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/_form.html.erb
<% action = (user.persisted? ? user_url(user) : users_url) %>
<% method = (user.persisted? ? "put" : "post") %>
<% message = (user.persisted? ? "Update user" : "Create user") %>

<form action="<%= action %>" method="post">
  <input
     name="_method"
     type="hidden"
     value="<%= method %>">
  <input
     name="authenticity_token"
     type="hidden"
     value="<%= form_authenticity_token %>">

  <label for="user_username">Username</label>
  <input
     id="user_username"
     name="user[username]"
     type="text">
  <br>

  <label for="user_password">Password</label>
  <input
     id="user_password"
     name="user[password]"
     type="password">
  <br>

  <input type="submit" value="<%= message %>">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forgetmenot</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if signed_in? %>
    <ul>
      <li>Signed in as: <%= current_user.username %></li>
      <li><%= button_to "Sign Out", api_session_url, :method => :delete %></li>
    </ul>
    <% else %>
    <p>
      <%= link_to "Sign In", new_api_session_url %> or
      <%= link_to "Sign up", new_api_user_url %>
    </p>
  <% end %>

  <hr>

  <% if flash[:errors] %>
    <h3>Please fix the following errors:</h3>
    <ul>
      <% flash[:errors].each do |error| %>
      <li><%= error %></li>
      <% end %>
    </ul>
  <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/site/root.html.erb
<div id="content"></div>
<script type="text/javascript">
  auth_token = "<%= "#{form_authenticity_token}".html_safe %>"
</script>